In [24]:
from pandas import read_csv
import numpy as np
import matplotlib.pyplot as plt

In [40]:
m_cld_df = read_csv("Clinic_DataPDBioStampRCStudy.csv")

m_id = m_cld_df['ID'].to_numpy()
m_truth = m_cld_df['Status'].to_numpy()=='Control'

m_truth = m_truth.astype(int)
m_gt = np.stack([m_id,m_truth]).T
m_gt.shape

np.save('gt.npy',m_gt)

In [49]:
main_folder = 'FullDataSet_PD-BioStampRC21'

In [50]:
def get_folder_and_dataset(id_no):
    id_string = f'{id_no:03d}'
    folder_name = id_string
    data_name = 'rh_ID' + id_string + 'Accel.csv'

    return main_folder+'//'+folder_name+'//'+data_name

data_name = get_folder_and_dataset(63)
read_csv(data_name)

Timestampms   AccelXg   AccelYg   AccelZg
0                  0 -0.406683 -0.953079  0.063050
1                 32 -0.375433 -0.901320  0.081605
2                 64 -0.373480 -0.909621  0.150454
3                 96 -0.373480 -0.937942  0.131411
4                128 -0.360784 -0.898878  0.151431
...              ...       ...       ...       ...
5171395    164784275  0.306218 -0.960891 -0.173770
5171396    164784307  0.315496 -0.948684 -0.170352
5171397    164784339  0.308171 -0.946731 -0.161074
5171398    164784371  0.316960 -0.945266 -0.167422
5171399    164784403  0.306218 -0.953567 -0.172793

[5171400 rows x 4 columns]

In [ ]:
def get_data_windows(id,n,window_size):
    data_name = get_folder_and_dataset(id)
    data = read_csv(data_name).to_numpy()
    print(data)
    top = np.max(data.shape)
    m_rand = np.random.randint(0,top,size=n)
    windows_list = []
    for i in m_rand:
        window = data[i:i+window_size,1:]
        window = np.sqrt(np.sum(np.pow(window,2),axis=1))
        windows_list.append(window)

    return np.array(windows_list)

get_data_windows(5,100,50).shape

[[ 0.00000000e+00 -3.21660182e-02 -7.36766613e-01  7.20775158e-01]
 [ 3.20000000e+01 -3.94903487e-02 -7.39696345e-01  7.03685054e-01]
 [ 6.40000000e+01 -3.46074617e-02 -7.35790036e-01  7.00267033e-01]
 ...
 [ 1.63271028e+08 -2.16250858e-01 -8.32959487e-01  4.91767758e-01]
 [ 1.63271059e+08 -1.68886854e-01 -8.39795529e-01  4.99580377e-01]
 [ 1.63271091e+08 -1.95254444e-01 -8.76905470e-01  5.24483101e-01]]
[1.01770003 1.02040005 1.02220797 1.02120277 1.01826996 1.03223135
 1.02478864 1.01675313 1.02165371 1.02475612 1.02314085 1.02498879
 1.02711584 1.02269598 1.0224381  1.02801194 1.01547185 1.02246349
 1.01982091 1.02962973 1.0310042  1.0300118  1.01546827 1.00982206
 1.03133651 1.02209708 1.02056836 1.02053604 1.02176123 1.0181863
 1.02410064 1.02652748 1.01979429 1.03089038 1.02147359 1.0206364
 1.01655279 1.02231222 1.02579651 1.0236561  1.01587585 1.02568166
 1.0227313  1.0251717  1.02442068 1.02231004 1.01569012 1.01921094
 1.02309194 1.02182266]
[1.01826498 1.02164499 1.01845922 

(100, 50)